// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3gjv9UHkclwHMA29HnbrfjfR-ka6loeM',
    appId: '1:125248632040:android:d03513fec28b4f3915055d',
    messagingSenderId: '125248632040',
    projectId: 'evento-9a40a',
    storageBucket: 'evento-9a40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBsNIfGwfyGdt4gw2qN2zUZkLuTfoWpw',
    appId: '1:125248632040:ios:8b96c9b0f7bdb10e15055d',
    messagingSenderId: '125248632040',
    projectId: 'evento-9a40a',
    storageBucket: 'evento-9a40a.appspot.com',
    androidClientId: '125248632040-90rro7mchltuk8nv7acu6c3r312iig6r.apps.googleusercontent.com',
    iosClientId: '125248632040-5jslsrf4cpfrecbp28298flr03u0t7g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );
}
